version: "3.9"
services:
  peekl:
    image: "peekl/peekl"
    links:
      - "redis:redis"
    volumes:
      - ./config.yaml:/usr/src/app/config.yaml

  redis:
    ports:
      - "6379:6379"
    image: "redislabs/redistimeseries"
